[profile.default]
src = "src"
out = "out"
build_info = true
extra_output = ["metadata", "storageLayout"]
libs = ["lib"]
ast = true
solc = "0.8.26"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
fs_permissions = [{ access = "read-write", path = "./deployments" }, { access = "read", path = "./" }]


[profile.ci]
fuzz = { runs = 20_000}  # Replace with your actual seed
verbosity = 4

[fuzz]
runs = 300  # Replace with your actual seed
seed = "0x1234567890abcdef"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
